[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:mosquitto]
command=mosquitto -c /etc/mosquitto/mosquitto.conf -v
autostart=true
autorestart=true
priority=10
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gateway-bridge]
command=/usr/local/bin/chirpstack-gateway-bridge -c /etc/chirpstack-gateway-bridge/gateway-bridge.toml
autostart=true
autorestart=true
priority=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:chirpstack]
command=/usr/local/bin/chirpstack -c /etc/chirpstack
autostart=true
autorestart=true
priority=30
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
